apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: amazon-clone
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-clone
spec:
  selector:
    matchLabels:
      app: amazon-clone
  replicas: 1
  template:
    metadata:
      labels:
        app: amazon-clone
    spec:
      containers:
      - name: amazon-clone
        image: kanika26/my-images:myfirstpush
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
